In [3]:
import numpy as np
a=np.array(([10,20,30],[50,80,70]))
print(a)
print("Array created:",a)

[[10 20 30]
 [50 80 70]]
Array created: [[10 20 30]
 [50 80 70]]


In [4]:
import numpy as np
a=np.zeros((3,5))
print("\n Array with zeros: \n",a)


 Array with zeros: 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
import numpy as np
d=np.random.random((3,3))
print("\n Random values: \n",d)


 Random values: 
 [[0.96215424 0.32525691 0.46348827]
 [0.59013654 0.30860514 0.77285216]
 [0.30485834 0.92448078 0.96127783]]


In [7]:
import numpy as np
e=np.arange(0,40,5)
print("\n A sequence array with steps 5: \n",e)



 A sequence array with steps 5: 
 [ 0  5 10 15 20 25 30 35]


In [8]:
import numpy as np
f=np. full((3,4),(7))
print(f)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [9]:
import numpy as op
arr=np.array([[1,2,3,4],[10,20,30,40],[11,22,33,44]])
newarr=arr.reshape(4,3)
print("\n Original array:\n",arr)
print("\n reshaped array:\n",newarr)


 Original array:
 [[ 1  2  3  4]
 [10 20 30 40]
 [11 22 33 44]]

 reshaped array:
 [[ 1  2  3]
 [ 4 10 20]
 [30 40 11]
 [22 33 44]]


In [10]:
flat=arr.flatten()
print("\n Original array \n",arr)
print("\n flatten array \n",flat)


 Original array 
 [[ 1  2  3  4]
 [10 20 30 40]
 [11 22 33 44]]

 flatten array 
 [ 1  2  3  4 10 20 30 40 11 22 33 44]


In [11]:
arr=np.array(([1,2,3,4],[10,20,30,40],[11,22,33,44]))
print("\n no. of dimensions:",arr.ndim)


 no. of dimensions: 2


In [12]:
arr=np.array(([1,2,3,4],[10,20,30,40],[11,22,33,44]))
print("\n shape of the array:",arr.shape)


 shape of the array: (3, 4)


In [13]:
import numpy as np
arr=np.array(([1,2,3,4],[10,20,30,40],[11,22,33,44]))
print("\n Array element type:",type(arr))


 Array element type: <class 'numpy.ndarray'>


In [14]:
arr=np.array(([1,2,3,4],[10,20,30,40],[11,22,33,44]))
newtype=arr.astype('f')
print("\n converted array element: \n",newtype)
print("converted array type:",newtype.dtype)
size=len(arr)
print("\n Size of array: \n",size)


 converted array element: 
 [[ 1.  2.  3.  4.]
 [10. 20. 30. 40.]
 [11. 22. 33. 44.]]
converted array type: float32

 Size of array: 
 3


In [15]:
size=len(arr)
print("\n size of array:\n",size)


 size of array:
 3
